"""empty message

Revision ID: 0.4.0
Revises: 4388426ad1af
Create Date: 2016-09-11 09:37:10.375130

"""

# revision identifiers, used by Alembic.
revision = '0.4.0'
down_revision = '4388426ad1af'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import house_tracker

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('outer_id_fd', mysql.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('batch_number', mysql.INTEGER(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('target_url', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('parameters', house_tracker.models.PickleType(), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('district_id', mysql.INTEGER(), nullable=True),
    sa.Column('community_id', mysql.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presale_permit',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('community_id', mysql.INTEGER(), nullable=False),
    sa.Column('serial_number', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('sale_date', sa.DATE(), nullable=True),
    sa.Column('total_number', mysql.INTEGER(), nullable=True),
    sa.Column('normal_number', mysql.INTEGER(), nullable=True),
    sa.Column('total_area', mysql.FLOAT(), nullable=True),
    sa.Column('normal_area', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'community', sa.Column('district_id', mysql.INTEGER(), nullable=True))
    op.add_column(u'community', sa.Column('location', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column(u'community', sa.Column('total_area', mysql.FLOAT(), nullable=True))
    op.add_column(u'community', sa.Column('total_number', mysql.INTEGER(), nullable=True))
    op.add_column(u'community', sa.Column('type', mysql.VARCHAR(length=64), nullable=False))
    op.alter_column(u'community', 'outer_id',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=True)
    op.create_foreign_key('district_id', 'community', 'district', ['district_id'], ['id'])
    op.drop_column(u'community', 'district')
    op.alter_column(u'community_record', 'house_download_finish',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column(u'community_record', 'house_parse_finish',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column(u'house', 'available',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column(u'house', 'new',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'house', 'new',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column(u'house', 'available',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column(u'community_record', 'house_parse_finish',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column(u'community_record', 'house_download_finish',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column(u'community', sa.Column('district', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=32), nullable=False))
    op.drop_constraint('district_id', 'community', type_='foreignkey')
    op.alter_column(u'community', 'outer_id',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=128),
               nullable=False)
    op.drop_column(u'community', 'type')
    op.drop_column(u'community', 'total_number')
    op.drop_column(u'community', 'total_area')
    op.drop_column(u'community', 'location')
    op.drop_column(u'community', 'district_id')
    op.drop_table('presale_permit')
    op.drop_table('job')
    op.drop_table('district')
    ### end Alembic commands ###
