"""empty message

Revision ID: 0.5.0
Revises: 0.4.0
Create Date: 2016-09-11 21:11:58.980484

"""

# revision identifiers, used by Alembic.
revision = '0.5.0'
down_revision = '0.4.0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'target_url',
           existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=1024),
           nullable=True)
    op.add_column('community', sa.Column('track_presale', sa.BOOLEAN(), nullable=True))
    op.add_column('community', sa.Column('presale_url_name', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('community', sa.Column('company', mysql.VARCHAR(length=1024), nullable=True))
    op.execute("update community set track_presale = true where type='fangdi'")
    op.execute("update job set type = 'presale_job' where type='community_job'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'track_presale')
    op.drop_column('community', 'presale_url_name')
    op.drop_column('community', 'company')
    op.execute("update job set type = 'community_job' where type='presale_job'")
    op.alter_column('job', 'target_url',
           existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=1024),
           nullable=False)
    ### end Alembic commands ###
