"""empty message

Revision ID: 0.6.0
Revises: 0.5.0
Create Date: 2016-10-15 14:19:01.564286

"""

# revision identifiers, used by Alembic.
revision = '0.6.0'
down_revision = '0.5.0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community', 'last_track_week', new_column_name='last_batch_number',
                    existing_type=mysql.INTEGER)
    op.alter_column('community_record', 'create_week', new_column_name='batch_number',
                    existing_type=mysql.INTEGER, nullable=False)
    op.alter_column('house', 'last_track_week', new_column_name='last_batch_number',
                    existing_type=mysql.INTEGER)
    op.alter_column('house_record', 'create_week', new_column_name='batch_number',
                    existing_type=mysql.INTEGER, nullable=False)
    op.alter_column('job', 'target_url', new_column_name='target_uri',
                    existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=1024))
    
    op.drop_column('community_record', 'house_parse_finish')
    op.drop_column('community_record', 'house_download_finish')
    
    op.add_column('job', sa.Column('house_id', mysql.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'job', 'house', ['house_id'], ['id'])
    
    
    op.create_table('area',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('district_id', mysql.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'community', sa.Column('area_id', mysql.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'community', 'area', ['area_id'], ['id'])
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community', type_='foreignkey')
    
    op.drop_column(u'community', 'area_id')
    op.drop_table('area')
    
    
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'house_id')
    
    op.add_column('community_record', sa.Column('house_download_finish', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('community_record', sa.Column('house_parse_finish', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    
    op.alter_column('job', 'target_uri', new_column_name='target_url',
                    existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=1024))
    op.alter_column('house_record', 'batch_number', new_column_name='create_week',
                    existing_type=mysql.INTEGER, nullable=False)
    op.alter_column('house', 'last_batch_number', new_column_name='last_track_week',
                    existing_type=mysql.INTEGER)
    op.alter_column('community_record', 'batch_number', new_column_name='create_week',
                    existing_type=mysql.INTEGER, nullable=False)
    op.alter_column('community', 'last_batch_number', new_column_name='last_track_week',
                    existing_type=mysql.INTEGER)
    
    ### end Alembic commands ###
