"""empty message

Revision ID: 0.7.0
Revises: 0.6.0
Create Date: 2016-11-05 12:08:09.877024

"""

# revision identifiers, used by Alembic.
revision = '0.7.0'
down_revision = '0.6.0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_record', sa.Column('average_price_change', mysql.INTEGER(), nullable=True))
    op.add_column('community_record', sa.Column('valid_average_price', mysql.INTEGER(), nullable=True))
    op.add_column('community', sa.Column('valid_average_price', mysql.INTEGER(), nullable=True))
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'valid_average_price')
    op.drop_column('community_record', 'valid_average_price')
    op.drop_column('community_record', 'average_price_change')
    ### end Alembic commands ###
