"""empty message

Revision ID: 0.8.0
Revises: 0.7.0
Create Date: 2016-12-07 18:54:08.378689

"""

# revision identifiers, used by Alembic.
revision = '0.8.0'
down_revision = '0.7.0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_sold_record',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('district_id', mysql.INTEGER(), nullable=True),
    sa.Column('area_id', mysql.INTEGER(), nullable=True),
    sa.Column('land_name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('boundary', mysql.TEXT(), nullable=True),
    sa.Column('record_no', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('sold_date', sa.DATE(), nullable=True),
    sa.Column('land_price', mysql.INTEGER(), nullable=True),
    sa.Column('company', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('land_area', mysql.INTEGER(), nullable=True),
    sa.Column('plot_ratio', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('land',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('sold_record_id', mysql.INTEGER(), nullable=True),
    sa.Column('district_id', mysql.INTEGER(), nullable=True),
    sa.Column('area_id', mysql.INTEGER(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('plot_ratio', mysql.FLOAT(), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['sold_record_id'], ['land_sold_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('land')
    op.drop_table('land_sold_record')
    ### end Alembic commands ###
