"""empty message

Revision ID: 2447d82bb6d6
Revises: 1.0.0
Create Date: 2018-02-05 11:15:14.646320

"""

# revision identifiers, used by Alembic.
revision = '1.1.0'
down_revision = '1.0.0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('date_to_market', sa.DATE(), nullable=True))
    op.add_column('house', sa.Column('last_purchase_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'last_purchase_date')
    op.drop_column('house', 'date_to_market')
    # ### end Alembic commands ###
