"""empty message

Revision ID: 63228340b6d0
Revises: d85197cecc08
Create Date: 2016-05-01 17:34:49.702708

"""

# revision identifiers, used by Alembic.
revision = '63228340b6d0'
down_revision = 'd85197cecc08'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('price_origin', sa.Integer(), nullable=False))
    op.drop_column('house', 'price_change')
    op.alter_column('house', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('house_record', sa.Column('price_change', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house_record', 'price_change')
    op.drop_column('house', 'price_origin')
    op.add_column('house', sa.Column('price_change', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('house', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    
    ### end Alembic commands ###
