"""empty message

Revision ID: d85197cecc08
Revises: f966a450a2e4
Create Date: 2016-04-26 19:38:06.248319

"""

# revision identifiers, used by Alembic.
revision = 'd85197cecc08'
down_revision = 'f966a450a2e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_record', sa.Column('miss_number', sa.Integer(), nullable=True))
    op.add_column('community_record', sa.Column('new_number', sa.Integer(), nullable=True))
    op.add_column('community_record', sa.Column('reduce_number', sa.Integer(), nullable=True))
    op.add_column('community_record', sa.Column('rise_number', sa.Integer(), nullable=True))
    op.add_column('community_record', sa.Column('valid_unchange_number', sa.Integer(), nullable=True))
    op.add_column('community_record', sa.Column('view_last_week', sa.Integer(), nullable=True))

    op.add_column('house', sa.Column('available_change_times', sa.Integer(), nullable=True))
    op.add_column('house', sa.Column('last_track_week', sa.Integer(), nullable=True))
    op.add_column('house', sa.Column('new', sa.Boolean(), nullable=True))
    op.add_column('house', sa.Column('price_change', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'price_change')
    op.drop_column('house', 'new')
    op.drop_column('house', 'last_track_week')
    op.drop_column('house', 'available_change_times')

    op.drop_column('community_record', 'view_last_week')
    op.drop_column('community_record', 'valid_unchange_number')
    op.drop_column('community_record', 'rise_number')
    op.drop_column('community_record', 'reduce_number')
    op.drop_column('community_record', 'new_number')
    op.drop_column('community_record', 'miss_number')
    ### end Alembic commands ###
