"""empty message

Revision ID: 4388426ad1af
Revises: 63228340b6d0
Create Date: 2016-05-07 10:41:53.862141

"""

# revision identifiers, used by Alembic.
revision = '4388426ad1af'
down_revision = '63228340b6d0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('house', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('house', 'price_origin',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('house', 'price_origin',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('house', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
   ### end Alembic commands ###
