"""empty message

Revision ID: ea8a76e277dc
Revises: 
Create Date: 2016-04-16 08:40:49.914337

"""

# revision identifiers, used by Alembic.
revision = 'ea8a76e277dc'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outer_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('average_price', sa.Integer(), nullable=True),
    sa.Column('house_available', sa.Integer(), nullable=True),
    sa.Column('sold_last_season', sa.Integer(), nullable=True),
    sa.Column('view_last_month', sa.Integer(), nullable=True),
    sa.Column('last_track_week', sa.Integer(), nullable=True),
    sa.Column('date_create', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Integer(), nullable=True),
    sa.Column('house_available', sa.Integer(), nullable=True),
    sa.Column('sold_last_season', sa.Integer(), nullable=True),
    sa.Column('view_last_month', sa.Integer(), nullable=True),
    sa.Column('house_download_finish', sa.Boolean(), nullable=True),
    sa.Column('house_parse_finish', sa.Boolean(), nullable=True),
    sa.Column('create_week', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('outer_id', sa.String(length=128), nullable=False),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(length=64), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('view_last_month', sa.Integer(), nullable=True),
    sa.Column('view_last_week', sa.Integer(), nullable=True),
    sa.Column('last_track_week', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('view_last_month', sa.Integer(), nullable=True),
    sa.Column('view_last_week', sa.Integer(), nullable=True),
    sa.Column('create_week', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house_records')
    op.drop_table('houses')
    op.drop_table('community_records')
    op.drop_table('communities')
    ### end Alembic commands ###
