"""empty message

Revision ID: f966a450a2e4
Revises: 
Create Date: 2016-04-23 20:29:22.012159

"""

# revision identifiers, used by Alembic.
revision = 'f966a450a2e4'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('outer_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('average_price', sa.Integer(), nullable=True),
    sa.Column('house_available', sa.Integer(), nullable=True),
    sa.Column('sold_last_season', sa.Integer(), nullable=True),
    sa.Column('view_last_month', sa.Integer(), nullable=True),
    sa.Column('last_track_week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Integer(), nullable=True),
    sa.Column('house_available', sa.Integer(), nullable=True),
    sa.Column('sold_last_season', sa.Integer(), nullable=True),
    sa.Column('view_last_month', sa.Integer(), nullable=True),
    sa.Column('house_download_finish', sa.Boolean(), nullable=True),
    sa.Column('house_parse_finish', sa.Boolean(), nullable=True),
    sa.Column('create_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('outer_id', sa.String(length=128), nullable=False),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(length=64), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('view_last_month', sa.Integer(), nullable=True),
    sa.Column('view_last_week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_record',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('view_last_month', sa.Integer(), nullable=True),
    sa.Column('view_last_week', sa.Integer(), nullable=True),
    sa.Column('create_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house_record')
    op.drop_table('house')
    op.drop_table('community_record')
    op.drop_table('community')
    ### end Alembic commands ###
